/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package music.playlist;

import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

import javax.swing.*;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author anushka
 */
public class Home extends javax.swing.JFrame {

    String user;
    /**
     * Creates new form Home
     */
    public Home(String username) {

        user = username;
        initComponents();
    }
    
    Connection con;
    PreparedStatement ps;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        helloDisplay = new javax.swing.JLabel();
        expBtn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        libraryBtn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        favBtn = new javax.swing.JLabel();
        exploreBtn = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        profileBtn = new javax.swing.JLabel();
        playlistBtn1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Silom", 1, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JUKEBOXX");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 240, -1));

        helloDisplay.setFont(new java.awt.Font("Optima", 1, 20)); // NOI18N
        helloDisplay.setForeground(new java.awt.Color(255, 255, 255));
        helloDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helloDisplay.setText("Hello, user!");
        jPanel1.add(helloDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 165, -1));

        expBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image (4)_prev_ui.png"))); // NOI18N
        expBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expBtnMouseClicked(evt);
            }
        });
        jPanel1.add(expBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 130, 130));

        jLabel4.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LIBRARY");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        libraryBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libraryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image (5)_prev_ui.png"))); // NOI18N
        libraryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libraryBtnMouseClicked(evt);
            }
        });
        jPanel1.add(libraryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 130, 130));

        jLabel5.setFont(new java.awt.Font("PT Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PLAY");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        favBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image (3)_prev_ui.png"))); // NOI18N
        favBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                favBtnMouseClicked(evt);
            }
        });
        jPanel1.add(favBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 130, 130));

        exploreBtn.setFont(new java.awt.Font("PT Sans", 1, 18)); // NOI18N
        exploreBtn.setForeground(new java.awt.Color(255, 255, 255));
        exploreBtn.setText("EXPLORE");
        exploreBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exploreBtnMouseClicked(evt);
            }
        });
        jPanel1.add(exploreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("PT Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FAVOURITES");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        profileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profileIcon.png"))); // NOI18N
        profileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnMouseClicked(evt);
            }
        });
        jPanel1.add(profileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 90, 70));

        playlistBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image (2)_prev_ui.png"))); // NOI18N
        playlistBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playlistBtn1MouseClicked(evt);
            }
        });
        jPanel1.add(playlistBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 130, 130));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg6 (2).jpeg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 604, 472));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseClicked
        Profile pf = new Profile(user);
        pf.setVisible(true);
        pf.pack();
        this.dispose();
    }//GEN-LAST:event_profileBtnMouseClicked

    private void expBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expBtnMouseClicked
        // TODO add your handling code here:
        Explore explore = new Explore(user);
        explore.setVisible(true);
        explore.pack();
        this.dispose();

    }//GEN-LAST:event_expBtnMouseClicked

    private void libraryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libraryBtnMouseClicked
        // TODO add your handling code here:
        Library lib = new Library(user);
        lib.setVisible(true);
        lib.pack();
        this.dispose();
        
 
    }//GEN-LAST:event_libraryBtnMouseClicked

    private void favBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favBtnMouseClicked
        // TODO add your handling code here:
        Favourites favourites = new Favourites(user);
        favourites.setVisible(true);
        favourites.pack();
        this.dispose();
    }//GEN-LAST:event_favBtnMouseClicked

    private void exploreBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exploreBtnMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_exploreBtnMouseClicked

    private void playlistBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playlistBtn1MouseClicked
        // TODO add your handling code here:
        Play play = new Play(user);
        play.setVisible(true);
        play.pack();
        this.dispose();
    }//GEN-LAST:event_playlistBtn1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home home = new Home("");
                home.setVisible(true);
                home.pack();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel expBtn;
    private javax.swing.JLabel exploreBtn;
    private javax.swing.JLabel favBtn;
    private javax.swing.JLabel helloDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel libraryBtn;
    private javax.swing.JLabel playlistBtn1;
    private javax.swing.JLabel profileBtn;
    // End of variables declaration//GEN-END:variables
}
