/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package music.playlist;

import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

import javax.swing.*;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author anushka
 */
public class Profile extends javax.swing.JFrame {

    String user;
    /**
     * Creates new form Profile
     */
    
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    public Profile(String username) {
        user = username;
            initComponents();

            try {
                String sql = "select Username, F_Name, L_Name, Address, Gender, DOB from user where Username = ?";  
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/music?user=root&password=Red@1989");
                ps = con.prepareStatement(sql);
                ps.setString(1, user);
                rs = ps.executeQuery();
                
                if (rs.next()) { 
                    nameD.setText(" " + (rs.getString("F_Name"))+" " +rs.getString("L_Name"));
                    usernameDisplay.setText(" " +rs.getString("Username"));
                    addressDisplay.setText(" " +rs.getString("Address"));
                    genderDisplay.setText(" " +rs.getString("Gender"));
                    dobDisplay.setText(" " +rs.getString("DOB"));  
                }
                
                String sql2 = "select count(*) as c from favourites where username = ?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/music?user=root&password=Red@1989");
                ps = con.prepareStatement(sql2);
                ps.setString(1, user);
                rs = ps.executeQuery();
                
                if (rs.next()) { 
                    favNumber.setText(" " +rs.getString("c"));
                }
            }
                
             catch(Exception e) {
                System.out.println("");
            }   
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        addressDisplay = new javax.swing.JLabel();
        usernameDisplay = new javax.swing.JLabel();
        favNumber = new javax.swing.JLabel();
        genderDisplay = new javax.swing.JLabel();
        dobDisplay = new javax.swing.JLabel();
        nameD = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 80));

        jLabel1.setFont(new java.awt.Font("Silom", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROFILE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 220, 52));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pIcon.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 90));

        jLabel7.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DOB");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        jLabel10.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Address");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("No. of favourites");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        addressDisplay.setFont(new java.awt.Font("Silom", 0, 16)); // NOI18N
        addressDisplay.setForeground(new java.awt.Color(255, 255, 255));
        addressDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(addressDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 170, 40));

        usernameDisplay.setFont(new java.awt.Font("Silom", 0, 16)); // NOI18N
        usernameDisplay.setForeground(new java.awt.Color(255, 255, 255));
        usernameDisplay.setText(" ");
        usernameDisplay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.add(usernameDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 170, 40));

        favNumber.setFont(new java.awt.Font("Silom", 0, 16)); // NOI18N
        favNumber.setForeground(new java.awt.Color(255, 255, 255));
        favNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(favNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 210, 40));

        genderDisplay.setFont(new java.awt.Font("Silom", 0, 16)); // NOI18N
        genderDisplay.setForeground(new java.awt.Color(255, 255, 255));
        genderDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(genderDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 80, 40));

        dobDisplay.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        dobDisplay.setForeground(new java.awt.Color(255, 255, 255));
        dobDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(dobDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 130, 40));

        nameD.setFont(new java.awt.Font("Silom", 1, 28)); // NOI18N
        nameD.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(nameD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 380, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg6 (2).jpeg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 600, 460));
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        // TODO add your handling code here:
        Home home = new Home(user);
        home.user = user;
        home.setVisible(true);
        home.pack();
        this.dispose();
    }//GEN-LAST:event_backBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Profile pf = new Profile("");
                pf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressDisplay;
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel dobDisplay;
    private javax.swing.JLabel favNumber;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel genderDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameD;
    private javax.swing.JLabel usernameDisplay;
    // End of variables declaration//GEN-END:variables
}
